Added: Finetuning, Function calling, Models
togethercomputer/openapi pull request #7
Opened 2024-04-03 16:30 UTC by Nutlope

2024-04-03 16:59 UTC, orangetin requested changes
left some comments, but otherwise looks great!

2024-04-03 16:59 UTC, orangetin commented on openapi.yaml
> +    post:
the cancel path is `/fine-tunes/{id}/cancel`. Ref [here](https://github.com/togethercomputer/together/blob/cc806455f3c5073dd01bdc59bade1f7873e653e8/src/together/resources/finetune.py#L154C39-L154C45)

2024-04-03 16:59 UTC, orangetin commented on openapi.yaml
> +  /fine-tunes/{id}/download:
download doesn't work like this currently, there is a redirection policy set up. maybe we just leave this out for now?

2024-04-03 16:59 UTC, orangetin commented on openapi.yaml
> +            - $ref: '#/components/schemas/ToolChoice'
I don't think we support tools/json mode for /v1/completions, right?

2024-04-03 17:19 UTC, orangetin commented on openapi.yaml
> +      summary: Upload a file
file upload doesn't work like this

2024-04-04 16:46 UTC, Nutlope commented on openapi.yaml
> +      summary: Upload a file
Decided not to include file upload anymore so I'm removing it (discussed)

2024-04-04 16:48 UTC, Nutlope commented on openapi.yaml
> +            - $ref: '#/components/schemas/ToolChoice'
Correct, moved to chat completions!

2024-04-04 17:03 UTC, Nutlope commented on openapi.yaml
> +  /fine-tunes/{id}/download:
Fixed this

2024-04-04 17:07 UTC, Nutlope commented on openapi.yaml
> +    post:
Added a cancel endpoint!

2024-04-05 04:49 UTC, orangetin requested changes
responded to the comment. One more change, can you add back the safety_model to `CompletionRequest`? safety model is supported, technically.

2024-04-05 04:49 UTC, orangetin commented on openapi.yaml
> +    post:
great! let's remove lines [410-424](https://github.com/togethercomputer/openapi/pull/7/files#diff-d910ba2ef878f7db0223a966b81c8b3f3b65027bb39e4431bb05140171eece39R410-R424) now?

2024-04-05 16:51 UTC, Nutlope commented on openapi.yaml
> +    post:
Good callout, done!

2024-04-05 16:52 UTC, Nutlope commented
> responded to the comment above. One more change, can you add back the safety_model to `CompletionRequest`? safety model is supported, technically.

Good catch, done!

2024-04-05 16:53 UTC, orangetin approved these changes

2024-04-05 16:54 UTC, merged